#!/bin/bash
#------------------------------------------------------------------------------------------
# This script performs initial smart recycle bin application deployment from target branch.
#
# Arguments accepted:
#   1 -> BRANCH - repo branch to synch with. Defaults to 'master' branch if not specified
#------------------------------------------------------------------------------------------
# User passed arguments:

BRANCH=${1:-"master"}
#------------------------------------------------------------------------------------------

sudo systemctl enable ssh
sudo systemctl start ssh
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install git
sudo apt-get -y install vim
pip install cayenne-mqtt
sudo pip install pip --upgrade
HOMEDIR=/home/pi/smart-recycling-bins-app/
mkdir ${HOMEDIR}
cd ${HOMEDIR}
git clone -b ${BRANCH} https://github.com/lab-dexter/smart-recycling-bins.git
cp ${HOMEDIR}smart-recycling-bins/app-sync.sh ${HOMEDIR}/
cat > /var/spool/cron/crontabs/root <<EOF
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/tmp/crontab.jvKBbk/crontab installed on Sun Feb 11 19:03:26 2018)
# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
0 * * * * sudo /home/pi/smart-recycling-bins-app/app-sync.sh ${BRANCH} >> /home/pi/smart-recycling-bins-app/smart-recycling-bins-sync.log
EOF
sudo cp ${HOMEDIR}smart-recycling-bins/recycle-bin.service /lib/systemd/system/recycle-bin.service
systemctl daemon-reload
systemctl enable recycle-bin.service
systemctl start recycle-bin.service
sudo reboot
