#!/bin/bash
sudo systemctl enable ssh
sudo systemctl start ssh
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install git
sudo apt-get -y install vim
pip install cayenne-mqtt
sudo pip install pip --upgrade
mkdir /home/pi/smart-recycling-bins-app
git clone https://github.com/lab-dexter/smart-recycling-bins.git
cp /home/pi/smart-recycling-bins-app/smart-recycling-bins/app-sync.sh /home/pi/smart-recycling-bins-app/
cat > /var/spool/cron/crontabs/root <<EOF
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/tmp/crontab.jvKBbk/crontab installed on Sun Feb 11 19:03:26 2018)
# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
0 * * * * sudo /home/pi/smart-recycle-bins-app/app-sync.sh master >> /home/pi/smart-recycle-bins-app/smart-recycle-bins-sync.log
EOF
sudo cp /home/pi/smart-recycling-bins-app/smart-recycling-bins/recycle-bin.service /lib/systemd/system/recycle-bin.service
systemctl daemon-reload
systemctl enable recycle-bin.service
systemctl start recycle-bin.service
sudo reboot
